### PR TITLE
Updated with final copy and some refactoring.

### PR DESCRIPTION
**Pull request by mmlin**

### CODE REVIEW

**Comment by mmlin** [comment]
🚀  Go ahead and deploy. Thanks!

**Comment by ikedumancas** [comment]
@mmlin Where did we use this again? Where do I deploy this?

**Comment by mmlin** [comment]
Never mind. I think this was a one time job. Can you confirm? If so, roll back the merge and delete this branch.

**Comment by ikedumancas** [comment]
I think this was a one time job where we had to email old clients.

**Pull request merged**
